default:      &default
  adapter:    postgresql
  encoding:   unicode
  username:   postgres
  password:   amendoim
  pool:       8
  host:       localhost

development:
  <<:         *default
  database:   two_web

test:
  <<:         *default
  database:   two_test

production:
  <<:         *default
  database:   two_production
